import React from 'react';
import LegalPage from '@/components/legal/LegalPage';

const AIDisclosure: React.FC = () => (
  <LegalPage
    title="AI Content Disclosure"
    subtitle="Transparency about synthetic media, in compliance with the FTC Act and EU AI Act (Regulation 2024/1689)."
  >
    <h2>1. Everything Here Is Synthetic</h2>
    <p>
      All personas, photos, voices, videos, and chat messages produced on All in 1 AI Model are{' '}
      <strong>generated by artificial intelligence</strong>. They are <strong>not real people</strong>. Any resemblance
      to a specific living or deceased person is unintended unless that person has provided verifiable written consent.
    </p>

    <h2>2. Why You're Seeing This Notice</h2>
    <p>
      Under <strong>Section 5 of the FTC Act</strong> (prohibition on deceptive practices) and <strong>Article 50 of the
      EU AI Act</strong>, providers and deployers of generative AI systems must clearly inform users when they are
      interacting with AI or viewing AI-generated content. We take that obligation seriously and disclose it in three places:
    </p>
    <ul>
      <li>An "AI" badge is rendered on every AI-generated image, video, and persona profile.</li>
      <li>Chat interfaces display a persistent "You are chatting with an AI" indicator.</li>
      <li>Synthetic media files are watermarked and embedded with C2PA-compatible provenance metadata where supported.</li>
    </ul>

    <h2>3. Creator Disclosure Obligations</h2>
    <p>
      If you operate a model on the Platform and republish content elsewhere (Instagram, TikTok, X, OnlyFans, Fanvue,
      etc.), you <strong>must</strong>:
    </p>
    <ul>
      <li>Mark posts as "AI-generated", "synthetic", or "virtual influencer" using the platform's native tag.</li>
      <li>Include a clear, conspicuous disclosure in the bio or caption (e.g., "100% AI-generated. Not a real person.").</li>
      <li>Never claim a synthetic persona is a real human, especially in romantic, sexual, or financial contexts.</li>
      <li>Comply with the FTC Endorsement Guides if your persona promotes products.</li>
    </ul>

    <h2>4. Prohibited Synthetic Content</h2>
    <ul>
      <li>Sexual content of minors or anyone appearing under 18 — strictly forbidden, reported to NCMEC.</li>
      <li>Non-consensual deepfakes of real, identifiable people.</li>
      <li>Election or political deepfakes intended to mislead voters.</li>
      <li>Synthetic content designed to defraud, defame, or impersonate.</li>
      <li>Medical, legal, or financial advice presented as if from a real licensed professional.</li>
    </ul>

    <h2>5. EU AI Act — Transparency Obligations (Article 50)</h2>
    <p>For users in the European Union we additionally confirm:</p>
    <ul>
      <li>You are interacting with an AI system. This is disclosed before any chat begins.</li>
      <li>Generated images, audio, and video are marked as "artificially generated or manipulated" in a machine-readable format.</li>
      <li>The Platform is <strong>not</strong> a high-risk AI system under Annex III. It is a general-purpose deployer of generative AI.</li>
      <li>You have the right to lodge a complaint with your national market-surveillance authority.</li>
    </ul>

    <h2>6. FTC Guidance — Endorsements &amp; Reviews</h2>
    <p>
      Per the FTC's 2023 update to the Endorsement Guides, if a synthetic persona endorses a product on or off the
      Platform, the post must disclose (a) that the persona is AI-generated and (b) any material connection to the
      advertiser. We provide a one-click "AI · Sponsored" badge for this purpose in the Studio.
    </p>

    <h2>7. Provenance &amp; Watermarking</h2>
    <p>
      All images generated on the Platform include a visible "AI" corner mark and embed C2PA Content Credentials
      describing the model, timestamp, and creator. Removing or obscuring the watermark to deceive viewers violates
      these Terms and may violate state deepfake disclosure laws (CA AB 730, TX SB 751, etc.).
    </p>

    <h2>8. Reporting Violations</h2>
    <p>
      Suspected undisclosed deepfakes or non-consensual synthetic media should be reported to{' '}
      <a href="mailto:trust@allin1aimodel.com">trust@allin1aimodel.com</a> or via the in-app "Report" button. We
      investigate within 24 hours.
    </p>

    <h2>9. Updates</h2>
    <p>
      Disclosure rules are evolving rapidly. We update this page when laws change and notify creators in-app of any
      new obligations.
    </p>
  </LegalPage>
);

export default AIDisclosure;
